# Generated by Django 3.1 on 2020-09-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
